In [61]:
import numpy as np
import random
import warnings
warnings.filterwarnings("ignore")
movie_id=np.arange(1301,2301)
display(movie_id.size)

1000

In [62]:
# creating user id for movies:

user_id=[]
for i in range(20201,20301):
    user_id.append(i)
user_id=np.array(user_id)
display(user_id.size)
display(user_id)

100

array([20201, 20202, 20203, 20204, 20205, 20206, 20207, 20208, 20209,
       20210, 20211, 20212, 20213, 20214, 20215, 20216, 20217, 20218,
       20219, 20220, 20221, 20222, 20223, 20224, 20225, 20226, 20227,
       20228, 20229, 20230, 20231, 20232, 20233, 20234, 20235, 20236,
       20237, 20238, 20239, 20240, 20241, 20242, 20243, 20244, 20245,
       20246, 20247, 20248, 20249, 20250, 20251, 20252, 20253, 20254,
       20255, 20256, 20257, 20258, 20259, 20260, 20261, 20262, 20263,
       20264, 20265, 20266, 20267, 20268, 20269, 20270, 20271, 20272,
       20273, 20274, 20275, 20276, 20277, 20278, 20279, 20280, 20281,
       20282, 20283, 20284, 20285, 20286, 20287, 20288, 20289, 20290,
       20291, 20292, 20293, 20294, 20295, 20296, 20297, 20298, 20299,
       20300])

In [63]:
# creating movie matrix to store user ratings:
movie_matrix=[]
for user in range(100):
    movies_rated_by_me=np.full(1000,-1)
    num_movies_rated=random.randint(0,999)
    movies_that_rate=random.sample(range(0,1000),num_movies_rated)
    for index in movies_that_rate:
        movies_rated_by_me[index]=random.randint(0,10)
    movie_matrix.append(movies_rated_by_me)
movie_matrix=np.array(movie_matrix)
len(movie_matrix)

100

In [64]:
print(movie_matrix)
print("shape of matrix: ",movie_matrix.shape)
print("number of elements: ",movie_matrix.size)
print("number of dimensions: ",movie_matrix.ndim)

[[-1 -1 -1 ... -1 -1 -1]
 [ 2  5  5 ...  1  9  0]
 [-1 -1  0 ... -1  4 -1]
 ...
 [ 4  7  5 ...  1  8  9]
 [ 3  5 -1 ...  8 -1  2]
 [-1 -1 -1 ... -1  0 -1]]
shape of matrix:  (100, 1000)
number of elements:  100000
number of dimensions:  2


In [65]:
# Reviews of 10 movie_experts, vertical wise:
expert_reviews=[]
for user in range(10):
    movie_rated_by_me=np.full(1000,-1)
    num_movie_rated=random.randint(0,999)
    movies_that_rate=random.sample(range(0,1000),num_movie_rated)
    for index in movie_rated_by_me:
        movie_rated_by_me[index]=random.randint(0,10)
    expert_reviews.append(movie_rated_by_me)
expert_reviews=np.array(expert_reviews)
print(expert_reviews)
print("Shape of matrix:   ",expert_reviews.shape)
    

[[-1 -1 -1 ... -1 -1  3]
 [-1 -1 -1 ... -1 -1  5]
 [-1 -1 -1 ... -1 -1  6]
 ...
 [-1 -1 -1 ... -1 -1  9]
 [-1 -1 -1 ... -1 -1  7]
 [-1 -1 -1 ... -1 -1 10]]
Shape of matrix:    (10, 1000)


In [66]:
#adding expert reviews with original reviews:
movie_matrix=np.vstack([movie_matrix,expert_reviews])
movie_matrix.shape

(110, 1000)

In [69]:
# adding new movies in matrix horizontal wise
new_movie_matrix=[]
for user in range(len(movie_matrix)):
    movie_rated_by_me=np.full(50,-1)
    num_movie_rated=random.randint(0,49)
    random.seed(num_movie_rated)
    movies_that_rate=random.sample(range(0,50),num_movie_rated)
    for index in movies_that_rate:
        movie_rated_by_me[index]=random.randint(0,10)
    new_movie_matrix.append(movie_rated_by_me)
new_movie_matrix=np.array(new_movie_matrix)
print(new_movie_matrix.shape)
new_movie_matrix

(110, 50)


array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [70]:
movie_matrix=np.hstack([movie_matrix,new_movie_matrix])
movie_matrix.shape

(110, 1050)

In [71]:
# generatiing new ids:
new_movie_ids=np.append(movie_id,np.arange(2301,2351))
new_movie_ids.size

1050

In [72]:
final_movie_ratings=[]
for i in range(len(new_movie_ids)):
    m=movie_matrix[:,i]#all rows and ith columns
    m=m[m>0]
    total_rate=m.sum()
    total_num_rating=m.size
    rating=m.mean()
    std=m.std()
    final_movie_ratings.append([new_movie_ids[i],rating,total_num_rating,std])
final_movie_ratings=np.array(final_movie_ratings)

In [73]:
final_movie_ratings

array([[1301.        ,    5.36170213,   47.        ,    2.79380418],
       [1302.        ,    5.68      ,   50.        ,    2.91506432],
       [1303.        ,    5.92307692,   39.        ,    2.57587043],
       ...,
       [2348.        ,           nan,    0.        ,           nan],
       [2349.        ,           nan,    0.        ,           nan],
       [2350.        ,           nan,    0.        ,           nan]])

In [74]:
#
x=final_movie_ratings[:,1]
old_range=x.max()-x.min()
new_range=(10-0)
final_movie_ratings[:,1]=(x-x.min())*(new_range/old_range)+0

In [76]:
display(final_movie_ratings)
display(final_movie_ratings.shape)

array([[1301.        ,           nan,   47.        ,    2.79380418],
       [1302.        ,           nan,   50.        ,    2.91506432],
       [1303.        ,           nan,   39.        ,    2.57587043],
       ...,
       [2348.        ,           nan,    0.        ,           nan],
       [2349.        ,           nan,    0.        ,           nan],
       [2350.        ,           nan,    0.        ,           nan]])

(1050, 4)

In [78]:
sorted_films=final_movie_ratings[final_movie_ratings[:,1].argsort()[::-1]]

array([[2350.        ,           nan,    0.        ,           nan],
       [1661.        ,           nan,   48.        ,    2.65230508],
       [1659.        ,           nan,   49.        ,    2.8854285 ],
       ...,
       [1993.        ,           nan,   43.        ,    2.9072558 ],
       [1992.        ,           nan,   47.        ,    2.78666553],
       [1301.        ,           nan,   47.        ,    2.79380418]])

In [79]:
display(sorted_films)

array([[2350.        ,           nan,    0.        ,           nan],
       [1661.        ,           nan,   48.        ,    2.65230508],
       [1659.        ,           nan,   49.        ,    2.8854285 ],
       ...,
       [1993.        ,           nan,   43.        ,    2.9072558 ],
       [1992.        ,           nan,   47.        ,    2.78666553],
       [1301.        ,           nan,   47.        ,    2.79380418]])

In [82]:
np.savetxt("ranked_movie_data.csv",sorted_films,delimiter=',')

In [84]:
data=np.genfromtxt("ranked_movie_data.csv",delimiter=',')
data

array([[2350.        ,           nan,    0.        ,           nan],
       [1661.        ,           nan,   48.        ,    2.65230508],
       [1659.        ,           nan,   49.        ,    2.8854285 ],
       ...,
       [1993.        ,           nan,   43.        ,    2.9072558 ],
       [1992.        ,           nan,   47.        ,    2.78666553],
       [1301.        ,           nan,   47.        ,    2.79380418]])